### ISSUE TITLE
Scale value

### ISSUE THREAD

**Issue by bh** [kezoo/sprite-webpack-plugin#4]
Hi,

is it possible to set a scale factor? This means for instance that an item on the sprite will be rendered in the half size of its size on the the sprite. In our current sprite implementaion we have something like this:

``` scss
.sprite {
    @include background(url('../static/webapp/images/sprite@2x.png'));
    background-repeat: no-repeat;
    background-size: $sprite-width/2 auto;
}
```

Where background-size will do the scaling.
